services:
  - type: web
    name: blog-backend
    env: python
    region: europe-west4
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_RUN_PORT
        value: 10000
    rootDir: backend
