services:
  - type: web
    name: blog-backend
    runtime: python
    buildCommand: poetry install
    startCommand: poetry run flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_APP
        value: app.py  # or your actual app entry point
      - key: FLASK_ENV
        value: production
